swagger: '2.0'
info:
  title: <%= name %>
  description: <%= description %>
  version: '1.0.0'
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /foo:
    get:
      operationId: fooController
      description: Return bar
      responses:
        200:
          description: bar
          schema:
            type: string
            example: bar
        400:
          description: Bad Request.
          schema:
            $ref: '#/definitions/ApiError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/ApiError'

  /swagger:
    x-swagger-pipe: swagger_raw
definitions:

  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
